
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opengauss.sig
  resources:
  - opengaussclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opengauss.sig
  resources:
  - opengaussclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opengauss.sig
  resources:
  - opengaussclusters/status
  verbs:
  - get
  - patch
  - update
